config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events, only: [:index, :show] do
    patch :create_message
  end

  namespace :api do
    resources :events, only: [] do
      resources :articles, only: [:index]
    end
  end
  namespace :admin do
    resources :events, only: [:edit, :update]
    resources :articles, only: [:destroy, :update]
  end

  root 'events#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Sidekiq::Web => '/sidekiq'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :event
  has_many :comments, dependent: :destroy

  serialize :keywords, Array
  serialize :pic_links, Array

  def post_date
    post_at.strftime("%_m/%d")
  end

  def start
    post_at
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :articles
  has_many :messages
  serialize :keywords, Array

  attr_accessor :hot, :trend, :articles_images

  def self.hot(num)
    Event.all
         .map do |e|
           OpenStruct.new(
             e.serializable_hash(
               methods: [:hot, :trend, :articles_images]
             )
           )
         end
         .sort_by do |e|
           e.hot
         end
         .last(10)
         .reverse
  end

  def hot
    event_comments = Comment.where(article_id: articles.ids)

    this_period_event_number = event_comments.where(commented_at: 2.hours.ago..Time.now).length
    prev_period_event_number = event_comments.where(commented_at: 4.hours.ago...2.hours.ago).length

    event_comments.length + (this_period_event_number - prev_period_event_number)
  end

  def trend
    event_comments = Comment.where(article_id: articles.ids)

    this_period_event_number = event_comments.where(commented_at: 2.hours.ago..Time.now).length
    prev_period_event_number = event_comments.where(commented_at: 4.hours.ago...2.hours.ago).length

    if prev_period_event_number == 0
      return 100
    else
      ((this_period_event_number - prev_period_event_number) / prev_period_event_number.to_f).round(2)*100
    end
  end

  def articles_images
    articles.map(&:pic_links).flatten
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/ptt_tag.rb
class PTTTag < ActiveRecord::Base
  # default scope

  # constant

  # attr macros

  # association macros
  has_many :raw_ptt_articles

  # validation macros
  validates :name, presence: true

  # callback macros

  # other macros

  # scope macros
end

app/models/raw_ptt_article.rb
class RawPTTArticle < ActiveRecord::Base
  # default scope

  # constant

  # attr macros

  # association macros
  belongs_to :ptt_tag

  # validation macros
  validates :url, presence: true

  # callback macros

  # other macros

  # scope macros
end

app/models/raw_ptt_comment.rb
class RawPTTComment < ActiveRecord::Base
  # default scope

  # constant

  # attr macros

  # association macros
  belongs_to :raw_ptt_article

  # validation macros
  validates :raw_ptt_article_id, presence: true

  # callback macros

  # other macros

  # scope macros
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.uid = auth.uid
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def email_required?
    false
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  def update
    @event = Event.find(params[:event_id])
    @article = Article.find(params[:id])
    @article.update!(article_params)
    redirect_to edit_admin_event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @article = @event.articles.find(params[:id])
    @article.destroy!
    redirect_to edit_admin_event_path(@event)
  end

  protected
  def article_params
    params.require(:article).permit(:title, pic_links: [])
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update!(event_params)
    redirect_to edit_admin_event_path(@event)
  end

  protected
  def event_params
    params.require(:event).permit(keywords: [])
  end
end

app/controllers/api/articles_controller.rb
class API::ArticlesController < API::BaseController
  def index
    @event = Event.find_by(id: params[:event_id])
    if @event
      render json: @event.articles.order(:post_at).includes(:comments)
    else
      render json: {articles:[]}
    end
  end
end

app/controllers/api/base_controller.rb
class API::BaseController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @hot_events = Event.hot(10)
  end

  def show
    begin
      @event = Event.find(params[:id])
      # .serializable_hash(methods: [:hot, :trend, :articles_images])
    rescue
      @event = Event.new(description: "o~hohohohohohohoho")
    end
  end

  def create_message
    @event = Event.find(params[:event_id])
    @message = @event.messages.build(content: params[:event][:messages][:content])
    @message.user = current_user || User.new(id: 1)
    @message.save!

    client = Apollo::Client.new(@event.id)
    client.push(@message, 'message')
    render json: {result: 'ok'}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/events/edit.html.slim
h1 = @event.description

= form_for [:admin, @event] do |f|
  .form-group
    label.control-label Description:
    = f.text_field :description, class: 'form-control'
  .form-group
    label.control-label Keywords:
    br
    - @event.keywords.each do |keyword|
      = text_field_tag 'event[keywords][]', keyword
  .form-group
    = f.submit "Update"

h2 = "Articles: #{@event.articles.count}"
- @event.articles.each_with_index do |article, index|
  h3 ------------------------------------------------
  = form_for [:admin, article] do |f|
    p = "Title: #{article.title}"
    p = "Author: #{article.arthor}"
    p = article.content
    p = article.keywords
    p = article.link
    .form-group
      label.control-label Pic Links:
      br
      - (0..4).each do |index|
        - if index < article.pic_links.length
          = image_tag(article.pic_links[index])
          = text_field_tag 'article[pic_links][]', article.pic_links[index], class: 'form-control'
        - else
          = text_field_tag 'article[pic_links][]', "", class: 'form-control'
    .form-group
      = hidden_field_tag 'event_id', @event.id
      = f.submit "Update", class: 'btn btn-primary'
  = button_to 'delete', admin_article_path(article), params: {event_id: @event.id}, method: "delete", data: { confirm: 'Are you sure?', disable_with: 'loading...' }, class: 'btn btn-danger'

app/views/events/index.html.slim
.container
  .FiredArea
    a.Card.Card--fired href=event_path(@hot_events.first.id)
      = image_tag("ribbon.svg", class: 'Card-FiredMark')
      .Card-Cover.lazy data-original=@hot_events.first.articles_images.first
      .Card-SubWrapper
        .Card-Comment
          = @hot_events.first.description
        .Card-Meta *{:class => @hot_events.first.trend > 0 ? "Card-Meta--up" : "Card-Meta--down"}
          .Card-Meta-Hot = "熱門值 #{@hot_events.first.hot}"
          .Card-Meta-Trend = "#{@hot_events.first.trend.abs}%"
  .row
    - @hot_events[1..-1].each do |event|
      .col-md-4.col-sm-6
        a.Card href=event_path(event.id)
          .Card-Cover.lazy data-original=event.articles_images.first
          .Card-SubWrapper
            .Card-Comment
              = event.description
            .Card-Meta *{:class => event.trend > 0 ? "Card-Meta--up" : "Card-Meta--down"}
              .Card-Meta-Hot = "熱門值 #{event.hot}"
              .Card-Meta-Trend = "#{event.trend.abs}%"

.Slogan 10 大最熱門事件，讓你真正掌握社會脈動

app/views/events/show.html.slim
#event-data style="display:none;" data-id=@event.id

.event-left-wrapper
  .Event
    .EventInfo
      .EventInfo-Meta *{:class => @event.trend > 0 ? "EventInfo-Meta--up" : "EventInfo-Meta--down"}
        .EventInfo-Meta-wrapper
          .EventInfo-Meta-Hot = "熱門值 #{@event.hot}/100"
          .EventInfo-Meta-Trend = "#{@event.trend.abs}%"
        .EventInfo-Meta-Title = @event.description
        .EventInfo-Meta-Social
          span.fb-share-button data-href=event_url(@event) data-layout="button_count"
    .Article.Article--in_event
      .Timeline#timeline
      .Article-Wrapper
        #right-arrow.Arrow.Arrow--in_event_right
          .Arrow-Image
          / .Arrow-Date 12.03 14:30AM
          .Arrow-Content
        #left-arrow.Arrow.Arrow--in_event_left
          .Arrow-Image
          / .Arrow-Date 12.03 14:30AM
          .Arrow-Content
        .Article-Content


.event-right-wrapper
  .Chatroom
    .Chatroom-List#chatroom-list
      / .Chatroom-MoreMessage#more-message
      /   |下方還有更多訊息喔
      / .Chatroom-Article
      /   .Chatroom-Article-Title
      /     |文章標題文章標題文章標題文章標題文章標題文章標題文章標題文章標題
      /   .Chatroom-Article-Comment.media
      /     .media-left
      /       =image_tag("message_icon_20x18")
      /     .media-body 說一些奇怪的話說一些奇怪的話說一些奇怪的話說一些奇怪的話
      /   .Chatroom-Article-Comment.media
      /     .media-left
      /       =image_tag("message_icon_20x18")
      /     .media-body 說一些奇怪的話說一些奇怪的話說一些奇怪的話說一些奇怪的話
      /   .Chatroom-Article-Comment.media
      /     .media-left
      /       =image_tag("message_icon_20x18")
      /     .media-body 說一些奇怪的話說一些奇怪的話說一些奇怪的話說一些奇怪的話
      /   a.Chatroom-Article-Link
      /     |< 回原文看更多連結

      / .Chatroom-Message.media
      /   .Chatroom-Message-UserPhoto.media-left
      /     =image_tag("ptt_icon_100x100_03")
      /   .media-body
      /     .Chatroom-Message-Username.media-heading
      /       |Username
      /     .Chatroom-Message-Content
      /       |說一些奇怪的話，說一些奇怪的話，說一些奇怪的話


    - if user_signed_in?
      = form_for @event, remote: true, url: {action: "create_message", event_id: @event.id}, html: {class: 'media Chatroom-InputArea'} do |f|
        .media-left.Chatroom-InputArea-UserPhoto
          = image_tag(current_user.image)
        = f.fields_for :messages do |message_form|
          .media-body.Chatroom-InputArea-Input
            = message_form.text_field :content, placeholder: '和別人一起聊一下你的想法吧...'
        = f.submit("送出訊息", class: 'Button Button--primary')
    - else
      .Chatroom-Login.Button.Button--fb Facebook 登入後留言

app/views/layouts/_footer.html.slim
footer.Footer
  .Footer-Copyright
    |©2015 端點 All Rights Reserved.

app/views/layouts/_navigation.html.slim
nav.Nav
  = image_tag("header_article.svg", class: 'Nav-LeftImage')
  .Nav-Dashed
  h1.Nav-Logo 端點
  .Nav-Dashed
  = image_tag("header_people.svg", class: 'Nav-LeftImage')

  - if user_signed_in?
    .dropdown.Nav-Status
      #dropdownMenu1.dropdown-toggle aria-expanded="true" aria-haspopup="true" data-toggle="dropdown" type="button"
        =image_tag(current_user.image)
        span.caret
      ul.dropdown-menu aria-labelledby="dropdownMenu1"
        li style="text-align: left; padding: 5px 20px;"
          = current_user.name
        li role="separator" class="divider"/
        li
          = link_to '登出', destroy_user_session_path, method: :delete
  - else
    =link_to('Facebook 登入', user_omniauth_authorize_path(:facebook), class: 'Nav-Login')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Armstrong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= body_class %>'>

  <div id="wrap">
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=820757474711654";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>

app/views/static_pages/index.html.erb
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>`

app/views/static_pages/index.slim
h1 welcome